/*===========================================================================*/
/* Module      = dr7f701310_irq.h                                            */
/* Version     = xx.xxx                                                      */
/*               extracted from device file xxxxxxxxxxxxxx                   */
/*               generated by xxxxxxxxxxxxxxxxxx                             */
/*===========================================================================*/
/*                                  COPYRIGHT                                */
/*===========================================================================*/
/* Copyright (c) 2013 by Renesas Electronics Europe GmbH,                    */
/*               a company of the Renesas Electronics Corporation            */
/*===========================================================================*/
/* Purpose:      Declarations of Interrupt Vector Table                      */
/*                                                                           */
/*===========================================================================*/
/*                                                                           */
/* Warranty Disclaimer                                                       */
/*                                                                           */
/* Because the Product(s) is licensed free of charge, there is no warranty   */
/* of any kind whatsoever and expressly disclaimed and excluded by Renesas,  */
/* either expressed or implied, including but not limited to those for       */
/* non-infringement of intellectual property, merchantability and/or         */
/* fitness for the particular purpose.                                       */
/* Renesas shall not have any obligation to maintain, service or provide bug */
/* fixes for the supplied Product(s) and/or the Application.                 */
/*                                                                           */
/* Each User is solely responsible for determining the appropriateness of    */
/* using the Product(s) and assumes all risks associated with its exercise   */
/* of rights under this Agreement, including, but not limited to the risks   */
/* and costs of program errors, compliance with applicable laws, damage to   */
/* or loss of data, programs or equipment, and unavailability or             */
/* interruption of operations.                                               */
/*                                                                           */
/* Limitation of Liability                                                   */
/*                                                                           */
/* In no event shall Renesas be liable to the User for any incidental,       */
/* consequential, indirect, or punitive damage (including but not limited    */
/* to lost profits) regardless of whether such liability is based on breach  */
/* of contract, tort, strict liability, breach of warranties, failure of     */
/* essential purpose or otherwise and even if advised of the possibility of  */
/* such damages. Renesas shall not be liable for any services or products    */
/* provided by third party vendors, developers or consultants identified or  */
/* referred to the User by Renesas in connection with the Product(s) and/or  */
/* the Application.                                                          */
/*                                                                           */
/*===========================================================================*/
/* Environment:                                                              */
/*              Device:         R7F701310                                    */
/*              IDE:            GHS Multi for V800  V6.xx or later           */
/*===========================================================================*/

#ifndef __R7F701310_IRQ_H
#define __R7F701310_IRQ_H

#define IRQ_TABLE_START                 0x00000200

#define RESET_ENABLE                    0x00000001

// #define SYSERR_ENABLE                   0x00000010

// #define FETRAPEX_ENABLE                 0x00000030

// #define EITRAP0_ENABLE                  0x00000040

// #define EITRAP1_ENABLE                  0x00000050

// #define RIEX_ENABLE                     0x00000060

// #define UCPOP_ENABLE                    0x00000080

// #define MIP_MDP_ENABLE                  0x00000090

// #define MAE_ENABLE                      0x000000C0

// #define FENMI_ENABLE                    0x000000E0

// #define FEINT_ENABLE                    0x000000F0

// #define EINTPRIO_0_ENABLE               0x00000100

// #define EINTPRIO_1_ENABLE               0x00000110

// #define EINTPRIO_2_ENABLE               0x00000120

// #define EINTPRIO_3_ENABLE               0x00000130

// #define EINTPRIO_4_ENABLE               0x00000140

// #define EINTPRIO_5_ENABLE               0x00000150

// #define EINTPRIO_6_ENABLE               0x00000160

// #define EINTPRIO_7_ENABLE               0x00000170

// #define EINTPRIO_8_ENABLE               0x00000180

// #define EINTPRIO_9_ENABLE               0x00000190

// #define EINTPRIO_10_ENABLE              0x000001A0

// #define EINTPRIO_11_ENABLE              0x000001B0

// #define EINTPRIO_12_ENABLE              0x000001C0

// #define EINTPRIO_13_ENABLE              0x000001D0

// #define EINTPRIO_14_ENABLE              0x000001E0

// #define EINTPRIO_15_ENABLE              0x000001F0

// #define INTTAUD0I0_ENABLE               (IRQ_TABLE_START + 0x00000000)

// #define INTCSIH2IC_1_ENABLE             (IRQ_TABLE_START + 0x00000000)


#endif /* __R7F701310_IRQ_H */
