/*===========================================================================*/
/* Module      = dr7f701412_irq.h                                            */
/* Version     = E1.00f                                                      */
/*               extracted from device file dr7f701412.dvf                   */
/*               generated by DeFiXRH850 0.7.2.3                             */
/*===========================================================================*/
/*                                  COPYRIGHT                                */
/*===========================================================================*/
/* Copyright (c) 2014 by Renesas Electronics Europe GmbH,                    */
/*               a company of the Renesas Electronics Corporation            */
/*===========================================================================*/
/* Purpose:      Declarations of Interrupt Vector Table                      */
/*                                                                           */
/*===========================================================================*/
/*                                                                           */
/* Warranty Disclaimer                                                       */
/*                                                                           */
/* Because the Product(s) is licensed free of charge, there is no warranty   */
/* of any kind whatsoever and expressly disclaimed and excluded by Renesas,  */
/* either expressed or implied, including but not limited to those for       */
/* non-infringement of intellectual property, merchantability and/or         */
/* fitness for the particular purpose.                                       */
/* Renesas shall not have any obligation to maintain, service or provide bug */
/* fixes for the supplied Product(s) and/or the Application.                 */
/*                                                                           */
/* Each User is solely responsible for determining the appropriateness of    */
/* using the Product(s) and assumes all risks associated with its exercise   */
/* of rights under this Agreement, including, but not limited to the risks   */
/* and costs of program errors, compliance with applicable laws, damage to   */
/* or loss of data, programs or equipment, and unavailability or             */
/* interruption of operations.                                               */
/*                                                                           */
/* Limitation of Liability                                                   */
/*                                                                           */
/* In no event shall Renesas be liable to the User for any incidental,       */
/* consequential, indirect, or punitive damage (including but not limited    */
/* to lost profits) regardless of whether such liability is based on breach  */
/* of contract, tort, strict liability, breach of warranties, failure of     */
/* essential purpose or otherwise and even if advised of the possibility of  */
/* such damages. Renesas shall not be liable for any services or products    */
/* provided by third party vendors, developers or consultants identified or  */
/* referred to the User by Renesas in connection with the Product(s) and/or  */
/* the Application.                                                          */
/*                                                                           */
/*===========================================================================*/
/* Environment:                                                              */
/*              Device:         R7F701412                                    */
/*              IDE:            GHS Multi for V800  V6.xx or later           */
/*===========================================================================*/

#ifndef __R7F701412_IRQ_H
#define __R7F701412_IRQ_H

#define IRQ_TABLE_START                 0x00000200u

#define RESET_ENABLE                    0x00000001u

// #define FENMI_ENABLE                    0x000000E0u

// #define FEINT_ENABLE                    0x000000F0u

// #define EINTPRIO_0_ENABLE               0x00000100u

// #define EINTPRIO_1_ENABLE               0x00000110u

// #define EINTPRIO_2_ENABLE               0x00000120u

// #define EINTPRIO_3_ENABLE               0x00000130u

// #define EINTPRIO_4_ENABLE               0x00000140u

// #define EINTPRIO_5_ENABLE               0x00000150u

// #define EINTPRIO_6_ENABLE               0x00000160u

// #define EINTPRIO_7_ENABLE               0x00000170u

// #define EINTPRIO_8_ENABLE               0x00000180u

// #define EINTPRIO_9_ENABLE               0x00000190u

// #define EINTPRIO_10_ENABLE              0x000001A0u

// #define EINTPRIO_11_ENABLE              0x000001B0u

// #define EINTPRIO_12_ENABLE              0x000001C0u

// #define EINTPRIO_13_ENABLE              0x000001D0u

// #define EINTPRIO_14_ENABLE              0x000001E0u

// #define EINTPRIO_15_ENABLE              0x000001F0u

// #define INTWDTA0_ENABLE                 (IRQ_TABLE_START + 0x00000000u)

// #define INTWDTA1_ENABLE                 (IRQ_TABLE_START + 0x00000004u)

// #define INTRTCA01S_ENABLE               (IRQ_TABLE_START + 0x00000008u)

// #define INTRTCA0AL_ENABLE               (IRQ_TABLE_START + 0x0000000Cu)

// #define INTRTCA0R_ENABLE                (IRQ_TABLE_START + 0x00000010u)

// #define INTAWOT0_ENABLE                 (IRQ_TABLE_START + 0x00000014u)

// #define INTP0_ENABLE                    (IRQ_TABLE_START + 0x00000018u)

// #define INTP1_ENABLE                    (IRQ_TABLE_START + 0x0000001Cu)

// #define INTP2_ENABLE                    (IRQ_TABLE_START + 0x00000020u)

// #define INTP3_ENABLE                    (IRQ_TABLE_START + 0x00000024u)

// #define INTP4_ENABLE                    (IRQ_TABLE_START + 0x00000028u)

// #define INTP5_ENABLE                    (IRQ_TABLE_START + 0x0000002Cu)

// #define INTP6_ENABLE                    (IRQ_TABLE_START + 0x00000030u)

// #define INTP7_ENABLE                    (IRQ_TABLE_START + 0x00000034u)

// #define INTP8_ENABLE                    (IRQ_TABLE_START + 0x00000038u)

// #define INTP9_ENABLE                    (IRQ_TABLE_START + 0x0000003Cu)

// #define INTP10_ENABLE                   (IRQ_TABLE_START + 0x00000040u)

// #define INTTAUB0I0_ENABLE               (IRQ_TABLE_START + 0x00000044u)

// #define INTTAUB0I1_ENABLE               (IRQ_TABLE_START + 0x00000048u)

// #define INTTAUB0I2_ENABLE               (IRQ_TABLE_START + 0x0000004Cu)

// #define INTTAUB0I3_ENABLE               (IRQ_TABLE_START + 0x00000050u)

// #define INTTAUB0I4_ENABLE               (IRQ_TABLE_START + 0x00000054u)

// #define INTTAUB0I5_ENABLE               (IRQ_TABLE_START + 0x00000058u)

// #define INTTAUB0I6_ENABLE               (IRQ_TABLE_START + 0x0000005Cu)

// #define INTTAUB0I7_ENABLE               (IRQ_TABLE_START + 0x00000060u)

// #define INTTAUB0I8_ENABLE               (IRQ_TABLE_START + 0x00000064u)

// #define INTTAUB0I9_ENABLE               (IRQ_TABLE_START + 0x00000068u)

// #define INTTAUB0I10_ENABLE              (IRQ_TABLE_START + 0x0000006Cu)

// #define INTTAUB0I11_ENABLE              (IRQ_TABLE_START + 0x00000070u)

// #define INTTAUB0I12_ENABLE              (IRQ_TABLE_START + 0x00000074u)

// #define INTTAUB0I13_ENABLE              (IRQ_TABLE_START + 0x00000078u)

// #define INTTAUB0I14_ENABLE              (IRQ_TABLE_START + 0x0000007Cu)

// #define INTTAUB0I15_ENABLE              (IRQ_TABLE_START + 0x00000080u)

// #define INTTAUB1I0_ENABLE               (IRQ_TABLE_START + 0x00000084u)

// #define INTTAUB1I1_ENABLE               (IRQ_TABLE_START + 0x00000088u)

// #define INTTAUB1I2_ENABLE               (IRQ_TABLE_START + 0x0000008Cu)

// #define INTTAUB1I3_ENABLE               (IRQ_TABLE_START + 0x00000090u)

// #define INTTAUB1I4_ENABLE               (IRQ_TABLE_START + 0x00000094u)

// #define INTTAUB1I5_ENABLE               (IRQ_TABLE_START + 0x00000098u)

// #define INTTAUB1I6_ENABLE               (IRQ_TABLE_START + 0x0000009Cu)

// #define INTTAUB1I7_ENABLE               (IRQ_TABLE_START + 0x000000A0u)

// #define INTTAUB1I8_ENABLE               (IRQ_TABLE_START + 0x000000A4u)

// #define INTTAUB1I9_ENABLE               (IRQ_TABLE_START + 0x000000A8u)

// #define INTTAUB1I10_ENABLE              (IRQ_TABLE_START + 0x000000ACu)

// #define INTTAUB1I11_ENABLE              (IRQ_TABLE_START + 0x000000B0u)

// #define INTTAUB1I12_ENABLE              (IRQ_TABLE_START + 0x000000B4u)

// #define INTTAUB1I13_ENABLE              (IRQ_TABLE_START + 0x000000B8u)

// #define INTTAUB1I14_ENABLE              (IRQ_TABLE_START + 0x000000BCu)

// #define INTTAUB1I15_ENABLE              (IRQ_TABLE_START + 0x000000C0u)

// #define INTTAUB2I0_ENABLE               (IRQ_TABLE_START + 0x000000C4u)

// #define INTTAUB2I1_ENABLE               (IRQ_TABLE_START + 0x000000C8u)

// #define INTTAUB2I2_ENABLE               (IRQ_TABLE_START + 0x000000CCu)

// #define INTTAUB2I3_ENABLE               (IRQ_TABLE_START + 0x000000D0u)

// #define INTTAUB2I4_ENABLE               (IRQ_TABLE_START + 0x000000D4u)

// #define INTTAUB2I5_ENABLE               (IRQ_TABLE_START + 0x000000D8u)

// #define INTTAUB2I6_ENABLE               (IRQ_TABLE_START + 0x000000DCu)

// #define INTTAUB2I7_ENABLE               (IRQ_TABLE_START + 0x000000E0u)

// #define INTTAUB2I8_ENABLE               (IRQ_TABLE_START + 0x000000E4u)

// #define INTTAUB2I9_ENABLE               (IRQ_TABLE_START + 0x000000E8u)

// #define INTTAUB2I10_ENABLE              (IRQ_TABLE_START + 0x000000ECu)

// #define INTTAUB2I11_ENABLE              (IRQ_TABLE_START + 0x000000F0u)

// #define INTTAUB2I12_ENABLE              (IRQ_TABLE_START + 0x000000F4u)

// #define INTTAUB2I13_ENABLE              (IRQ_TABLE_START + 0x000000F8u)

// #define INTTAUB2I14_ENABLE              (IRQ_TABLE_START + 0x000000FCu)

// #define INTTAUB2I15_ENABLE              (IRQ_TABLE_START + 0x00000100u)

// #define INTADCE0TSN_ENABLE              (IRQ_TABLE_START + 0x00000104u)

// #define INTADCE0I1_ENABLE               (IRQ_TABLE_START + 0x00000108u)

// #define INTADCE0I2_ENABLE               (IRQ_TABLE_START + 0x0000010Cu)

// #define INTADCE0I3_ENABLE               (IRQ_TABLE_START + 0x00000110u)

// #define INTRCANGERR_ENABLE              (IRQ_TABLE_START + 0x00000114u)

// #define INTRCANGRECC_ENABLE             (IRQ_TABLE_START + 0x00000118u)

// #define INTRCAN0ERR_ENABLE              (IRQ_TABLE_START + 0x0000011Cu)

// #define INTRCAN0REC_ENABLE              (IRQ_TABLE_START + 0x00000120u)

// #define INTRCAN0TRX_ENABLE              (IRQ_TABLE_START + 0x00000124u)

// #define INTCSIGT0IRE_ENABLE             (IRQ_TABLE_START + 0x00000128u)

// #define INTCSIG0IR_ENABLE               (IRQ_TABLE_START + 0x0000012Cu)

// #define INTCSIG0IC_ENABLE               (IRQ_TABLE_START + 0x00000130u)

// #define INTCSIH0IRE_ENABLE              (IRQ_TABLE_START + 0x00000134u)

// #define INTCSIH0IR_ENABLE               (IRQ_TABLE_START + 0x00000138u)

// #define INTCSIH0IC_ENABLE               (IRQ_TABLE_START + 0x0000013Cu)

// #define INTCSIH0IJC_ENABLE              (IRQ_TABLE_START + 0x00000140u)

// #define INTRLIN30UR2_ENABLE             (IRQ_TABLE_START + 0x00000144u)

// #define INTRLIN30UR1_ENABLE             (IRQ_TABLE_START + 0x00000148u)

// #define INTRLIN30UR0_ENABLE             (IRQ_TABLE_START + 0x0000014Cu)

// #define INTRLIN31UR2_ENABLE             (IRQ_TABLE_START + 0x00000150u)

// #define INTRLIN31UR1_ENABLE             (IRQ_TABLE_START + 0x00000154u)

// #define INTRLIN31UR0_ENABLE             (IRQ_TABLE_START + 0x00000158u)

// #define INTSG0TI_ENABLE                 (IRQ_TABLE_START + 0x0000015Cu)

// #define INTSG1TI_ENABLE                 (IRQ_TABLE_START + 0x00000160u)

// #define INTSG2TI_ENABLE                 (IRQ_TABLE_START + 0x00000164u)

// #define INTSG3TI_ENABLE                 (IRQ_TABLE_START + 0x00000168u)

// #define INTSG4TI_ENABLE                 (IRQ_TABLE_START + 0x0000016Cu)

// #define INTDCUTDI_ENABLE                (IRQ_TABLE_START + 0x00000170u)

// #define INTDMAERR_ENABLE                (IRQ_TABLE_START + 0x00000174u)

// #define INTDMA0_ENABLE                  (IRQ_TABLE_START + 0x00000178u)

// #define INTDMA1_ENABLE                  (IRQ_TABLE_START + 0x0000017Cu)

// #define INTDMA2_ENABLE                  (IRQ_TABLE_START + 0x00000180u)

// #define INTDMA3_ENABLE                  (IRQ_TABLE_START + 0x00000184u)

// #define INTDMA4_ENABLE                  (IRQ_TABLE_START + 0x00000188u)

// #define INTDMA5_ENABLE                  (IRQ_TABLE_START + 0x0000018Cu)

// #define INTDMA6_ENABLE                  (IRQ_TABLE_START + 0x00000190u)

// #define INTDMA7_ENABLE                  (IRQ_TABLE_START + 0x00000194u)

// #define INTDMA8_ENABLE                  (IRQ_TABLE_START + 0x00000198u)

// #define INTDMA9_ENABLE                  (IRQ_TABLE_START + 0x0000019Cu)

// #define INTDMA10_ENABLE                 (IRQ_TABLE_START + 0x000001A0u)

// #define INTDMA11_ENABLE                 (IRQ_TABLE_START + 0x000001A4u)

// #define INTDMA12_ENABLE                 (IRQ_TABLE_START + 0x000001A8u)

// #define INTDMA13_ENABLE                 (IRQ_TABLE_START + 0x000001ACu)

// #define INTDMA14_ENABLE                 (IRQ_TABLE_START + 0x000001B0u)

// #define INTDMA15_ENABLE                 (IRQ_TABLE_START + 0x000001B4u)

// #define INTRIIC0LEE_ENABLE              (IRQ_TABLE_START + 0x000001B8u)

// #define INTRIIC0RI_ENABLE               (IRQ_TABLE_START + 0x000001BCu)

// #define INTRIIC0TI_ENABLE               (IRQ_TABLE_START + 0x000001C0u)

// #define INTRIIC0TEI_ENABLE              (IRQ_TABLE_START + 0x000001C4u)

// #define INTRIIC1LEE_ENABLE              (IRQ_TABLE_START + 0x000001C8u)

// #define INTRIIC1RI_ENABLE               (IRQ_TABLE_START + 0x000001CCu)

// #define INTRIIC1TI_ENABLE               (IRQ_TABLE_START + 0x000001D0u)

// #define INTRIIC1TEI_ENABLE              (IRQ_TABLE_START + 0x000001D4u)

// #define INTRCAN1ERR_ENABLE              (IRQ_TABLE_START + 0x000001D8u)

// #define INTRCAN1REC_ENABLE              (IRQ_TABLE_START + 0x000001DCu)

// #define INTRCAN1TRX_ENABLE              (IRQ_TABLE_START + 0x000001E0u)

// #define INTTAUJ0I0_ENABLE               (IRQ_TABLE_START + 0x000001E4u)

// #define INTTAUJ0I1_ENABLE               (IRQ_TABLE_START + 0x000001E8u)

// #define INTTAUJ0I2_ENABLE               (IRQ_TABLE_START + 0x000001ECu)

// #define INTTAUJ0I3_ENABLE               (IRQ_TABLE_START + 0x000001F0u)

// #define INTOSTM0_ENABLE                 (IRQ_TABLE_START + 0x000001F4u)

// #define INTOSTM1_ENABLE                 (IRQ_TABLE_START + 0x000001F8u)

// #define INTCSIGT1IRE_ENABLE             (IRQ_TABLE_START + 0x000001FCu)

// #define INTCSIG1IR_ENABLE               (IRQ_TABLE_START + 0x00000200u)

// #define INTCSIG1IC_ENABLE               (IRQ_TABLE_START + 0x00000204u)

// #define INTCSIGT2IRE_ENABLE             (IRQ_TABLE_START + 0x00000208u)

// #define INTCSIG2IR_ENABLE               (IRQ_TABLE_START + 0x0000020Cu)

// #define INTCSIG2IC_ENABLE               (IRQ_TABLE_START + 0x00000210u)

// #define INTCSIGT3IRE_ENABLE             (IRQ_TABLE_START + 0x00000214u)

// #define INTCSIG3IR_ENABLE               (IRQ_TABLE_START + 0x00000218u)

// #define INTCSIG3IC_ENABLE               (IRQ_TABLE_START + 0x0000021Cu)

// #define INTCSIH1IRE_ENABLE              (IRQ_TABLE_START + 0x00000220u)

// #define INTCSIH1IR_ENABLE               (IRQ_TABLE_START + 0x00000224u)

// #define INTCSIH1IC_ENABLE               (IRQ_TABLE_START + 0x00000228u)

// #define INTCSIH1IJC_ENABLE              (IRQ_TABLE_START + 0x0000022Cu)

// #define INTQFULL_ENABLE                 (IRQ_TABLE_START + 0x00000230u)

// #define INTPWGA0_ENABLE                 (IRQ_TABLE_START + 0x00000234u)

// #define INTPWGA1_ENABLE                 (IRQ_TABLE_START + 0x00000238u)

// #define INTPWGA2_ENABLE                 (IRQ_TABLE_START + 0x0000023Cu)

// #define INTPWGA3_ENABLE                 (IRQ_TABLE_START + 0x00000240u)

// #define INTPWGA4_ENABLE                 (IRQ_TABLE_START + 0x00000244u)

// #define INTPWGA5_ENABLE                 (IRQ_TABLE_START + 0x00000248u)

// #define INTPWGA6_ENABLE                 (IRQ_TABLE_START + 0x0000024Cu)

// #define INTPWGA7_ENABLE                 (IRQ_TABLE_START + 0x00000250u)

// #define INTPWGA8_ENABLE                 (IRQ_TABLE_START + 0x00000254u)

// #define INTPWGA9_ENABLE                 (IRQ_TABLE_START + 0x00000258u)

// #define INTPWGA10_ENABLE                (IRQ_TABLE_START + 0x0000025Cu)

// #define INTPWGA11_ENABLE                (IRQ_TABLE_START + 0x00000260u)

// #define INTPWGA12_ENABLE                (IRQ_TABLE_START + 0x00000264u)

// #define INTPWGA13_ENABLE                (IRQ_TABLE_START + 0x00000268u)

// #define INTPWGA14_ENABLE                (IRQ_TABLE_START + 0x0000026Cu)

// #define INTPWGA15_ENABLE                (IRQ_TABLE_START + 0x00000270u)

// #define INTPWGA16_ENABLE                (IRQ_TABLE_START + 0x00000274u)

// #define INTPWGA17_ENABLE                (IRQ_TABLE_START + 0x00000278u)

// #define INTPWGA18_ENABLE                (IRQ_TABLE_START + 0x0000027Cu)

// #define INTPWGA19_ENABLE                (IRQ_TABLE_START + 0x00000280u)

// #define INTPWGA20_ENABLE                (IRQ_TABLE_START + 0x00000284u)

// #define INTPWGA21_ENABLE                (IRQ_TABLE_START + 0x00000288u)

// #define INTPWGA22_ENABLE                (IRQ_TABLE_START + 0x0000028Cu)

// #define INTPWGA23_ENABLE                (IRQ_TABLE_START + 0x00000290u)

// #define INTICUSTWRDY_ENABLE             (IRQ_TABLE_START + 0x00000294u)

// #define INTICUSTRRDY_ENABLE             (IRQ_TABLE_START + 0x00000298u)

// #define INTSCI30RXI_ENABLE              (IRQ_TABLE_START + 0x000002A0u)

// #define INTSCI30TXI_ENABLE              (IRQ_TABLE_START + 0x000002A4u)

// #define INTSCI30TEI_ENABLE              (IRQ_TABLE_START + 0x000002A8u)

// #define INTFLERR_ENABLE                 (IRQ_TABLE_START + 0x000002ACu)

// #define INTFLENDNM_ENABLE               (IRQ_TABLE_START + 0x000002B0u)

// #define INTLCBI0RDY_ENABLE              (IRQ_TABLE_START + 0x000002B8u)

// #define INTLCBI0EMPTY_ENABLE            (IRQ_TABLE_START + 0x000002BCu)

// #define INTLCBI0HALF_ENABLE             (IRQ_TABLE_START + 0x000002C0u)

// #define INTLCBI0FULL_ENABLE             (IRQ_TABLE_START + 0x000002C4u)

// #define INTLCBI0QTR_ENABLE              (IRQ_TABLE_START + 0x000002C8u)

// #define INTLCBI03QTR_ENABLE             (IRQ_TABLE_START + 0x000002CCu)

// #define INTRCAN2ERR_ENABLE              (IRQ_TABLE_START + 0x000002D0u)

// #define INTRCAN2REC_ENABLE              (IRQ_TABLE_START + 0x000002D4u)

// #define INTRCAN2TRX_ENABLE              (IRQ_TABLE_START + 0x000002D8u)

// #define INTPCMP0FFIL_ENABLE             (IRQ_TABLE_START + 0x000002DCu)

// #define INTPCMP0FERR_ENABLE             (IRQ_TABLE_START + 0x000002E0u)

// #define INTISM0REACHED_ENABLE           (IRQ_TABLE_START + 0x000002E4u)

// #define INTISM0DONE_ENABLE              (IRQ_TABLE_START + 0x000002E8u)

// #define INTISM0ZPDAD_ENABLE             (IRQ_TABLE_START + 0x000002ECu)

// #define INTSSIF0_ENABLE                 (IRQ_TABLE_START + 0x000002F4u)

// #define INTSSIF0RX_ENABLE               (IRQ_TABLE_START + 0x000002F8u)

// #define INTSSIF0TX_ENABLE               (IRQ_TABLE_START + 0x000002FCu)

// #define INTSSIF1_ENABLE                 (IRQ_TABLE_START + 0x00000300u)

// #define INTSSIF1RX_ENABLE               (IRQ_TABLE_START + 0x00000304u)

// #define INTSSIF1TX_ENABLE               (IRQ_TABLE_START + 0x00000308u)

// #define INTSDRB0_ENABLE                 (IRQ_TABLE_START + 0x0000030Cu)

// #define INTGPU2D0PAUSE_ENABLE           (IRQ_TABLE_START + 0x00000310u)

// #define INTGPU2D0SYNC_ENABLE            (IRQ_TABLE_START + 0x00000314u)

// #define INTGPU2D0SP_ENABLE              (IRQ_TABLE_START + 0x00000318u)

// #define INTVDCE0ERR_ENABLE              (IRQ_TABLE_START + 0x0000031Cu)

// #define INTVDCE0GR3VBLANK_ENABLE        (IRQ_TABLE_START + 0x00000320u)

// #define INTVDCE0S0VIVSYNC_ENABLE        (IRQ_TABLE_START + 0x00000324u)

// #define INTVDCE0S0LOVSYNC_ENABLE        (IRQ_TABLE_START + 0x00000328u)

// #define INTVDCE0GR3VLINE_ENABLE         (IRQ_TABLE_START + 0x0000032Cu)

// #define INTVDCE0S0VFIELD_ENABLE         (IRQ_TABLE_START + 0x00000330u)

// #define INTVDCE0S0WLINE_ENABLE          (IRQ_TABLE_START + 0x00000334u)

// #define INTVDCE0S1LOVSYNC_ENABLE        (IRQ_TABLE_START + 0x00000338u)

// #define INTVDCE0S1WLINE_ENABLE          (IRQ_TABLE_START + 0x0000033Cu)

// #define INTVDCE0OIRVIVSYNC_ENABLE       (IRQ_TABLE_START + 0x00000340u)

// #define INTVDCE0OIRLOVSYNC_ENABLE       (IRQ_TABLE_START + 0x00000344u)

// #define INTVDCE0OIRVLINE_ENABLE         (IRQ_TABLE_START + 0x00000348u)

// #define INTVDCE0OIRWLINE_ENABLE         (IRQ_TABLE_START + 0x0000034Cu)

// #define INTRLIN32UR2_ENABLE             (IRQ_TABLE_START + 0x0000035Cu)

// #define INTRLIN32UR1_ENABLE             (IRQ_TABLE_START + 0x00000360u)

// #define INTRLIN32UR0_ENABLE             (IRQ_TABLE_START + 0x00000364u)

// #define INTRLIN33UR2_ENABLE             (IRQ_TABLE_START + 0x00000368u)

// #define INTRLIN33UR1_ENABLE             (IRQ_TABLE_START + 0x0000036Cu)

// #define INTRLIN33UR0_ENABLE             (IRQ_TABLE_START + 0x00000370u)

// #define INTVDCE1ERR_ENABLE              (IRQ_TABLE_START + 0x00000374u)

// #define INTVDCE1GR3VBLANK_ENABLE        (IRQ_TABLE_START + 0x00000378u)

// #define INTVDCE1S0VIVSYNC_ENABLE        (IRQ_TABLE_START + 0x0000037Cu)

// #define INTVDCE1S0LOVSYNC_ENABLE        (IRQ_TABLE_START + 0x00000380u)

// #define INTVDCE1GR3VLINE_ENABLE         (IRQ_TABLE_START + 0x00000384u)

// #define INTVDCE1S0VFIELD_ENABLE         (IRQ_TABLE_START + 0x00000388u)

// #define INTVDCE1S0WLINE_ENABLE          (IRQ_TABLE_START + 0x0000038Cu)

// #define INTVDCE1S1LOVSYNC_ENABLE        (IRQ_TABLE_START + 0x00000390u)

// #define INTVDCE1S1WLINE_ENABLE          (IRQ_TABLE_START + 0x00000394u)

// #define INTVDCE1OIRVIVSYNC_ENABLE       (IRQ_TABLE_START + 0x00000398u)

// #define INTVDCE1OIRLOVSYNC_ENABLE       (IRQ_TABLE_START + 0x0000039Cu)

// #define INTVDCE1OIRVLINE_ENABLE         (IRQ_TABLE_START + 0x000003A0u)

// #define INTVDCE1OIRWLINE_ENABLE         (IRQ_TABLE_START + 0x000003A4u)

// #define INTMLBB0STA0_ENABLE             (IRQ_TABLE_START + 0x000003A8u)

// #define INTMLBB0STA1_ENABLE             (IRQ_TABLE_START + 0x000003ACu)

// #define INTMLBB0SYS_ENABLE              (IRQ_TABLE_START + 0x000003B0u)

// #define INTMLBB0HBI_ENABLE              (IRQ_TABLE_START + 0x000003B4u)

// #define INTMIPI0OVF_ENABLE              (IRQ_TABLE_START + 0x000003B8u)

// #define INTMIPI0CTL_ENABLE              (IRQ_TABLE_START + 0x000003BCu)

// #define INTVOWE0_ENABLE                 (IRQ_TABLE_START + 0x000003C0u)

// #define INTJCU0EDI_ENABLE               (IRQ_TABLE_START + 0x000003C8u)

// #define INTJCU0DTI_ENABLE               (IRQ_TABLE_START + 0x000003CCu)

// #define INTETNB0LINE0_ENABLE            (IRQ_TABLE_START + 0x000003D0u)

// #define INTETNB0LINE1_ENABLE            (IRQ_TABLE_START + 0x000003D4u)

// #define INTETNB0LINE2_ENABLE            (IRQ_TABLE_START + 0x000003D8u)

// #define INTETNB0LINE3_ENABLE            (IRQ_TABLE_START + 0x000003DCu)

// #define INTMISRERR_ENABLE               (IRQ_TABLE_START + 0x000003E0u)

// #define INTVPISG1OVFERR_ENABLE          (IRQ_TABLE_START + 0x000003E4u)

// #define INTVPISG2OVFERR_ENABLE          (IRQ_TABLE_START + 0x000003E8u)

// #define INTVPISG3OVFERR_ENABLE          (IRQ_TABLE_START + 0x000003ECu)

// #define INTVPISG5OVFERR_ENABLE          (IRQ_TABLE_START + 0x000003F4u)

// #define INTBUSERR_ENABLE                (IRQ_TABLE_START + 0x000003FCu)



#endif /* __R7F701412_IRQ_H */
