/****************************************************************************
 *  License : All rights reserved for TES Electronic Solutions GmbH
 *            See included /docs/license.txt for details
 *  Project : D/AVE HD
 *  Purpose : Compiletime settings, specifics for Renesas (D1x) platform
 ****************************************************************************
 * Version Control Information :
 *  $Revision: 6223 $
 *  $Date: 2015-10-07 18:08:29 +0200 (Mi, 07 Okt 2015) $
 *  $LastChangedBy: annabelle.agez $
 ****************************************************************************
 * Change History (autogenerated):
 ****************************************************************************/    

#ifndef DAVEHD_SETTINGS_D1X_H_INCLUDED
#define DAVEHD_SETTINGS_D1X_H_INCLUDED

#include "davehd_device_data_size_ree.h"

#ifdef DHD_DRIVER_DEBUG
  #define DHD_DEBUG_MODE
  #define DHD_DEBUG_GUARDED_LOOPS
  #define DHD_KERNEL_DEBUG
  #define DHD_KERNEL_DEBUG_ERROR
  #define DHD_KERNEL_TLIST_SUPPORT
  /*#define DHD_KERNEL_DEBUG_MEMORY*/
#endif

#define DHD_SUPPORT_CASSERT    
#undef DHD_CACHELINE_SIZE
#define DHD_CACHELINE_SIZE             64    
#undef DHD_VIDMEM_MINALIGN_LOG2
#define DHD_VIDMEM_MINALIGN_LOG2       7
#undef DHD_MAX_CPU_REGISTER_ACCESS
#define DHD_MAX_CPU_REGISTER_ACCESS    1024     /* architecture can only CPU access the first 4 kB of DHD register space*/
#undef DHD_MIN_JOB_SIZE
#define DHD_MIN_JOB_SIZE                512

#define DHD_GUARDED_LOOPS
#define DHD_JOB_CHECKSUM_SUPPORTED

#endif /* DAVEHD_SETTINGS_D1X_H_INCLUDED*/
