/****************************************************************************
 *  License : All rights reserved for TES Electronic Solutions GmbH
 *            See included /docs/license.txt for details
 *  Project : D/AVE HD
 *  Purpose : Hardware specific compiletime settings
 ****************************************************************************
 * Version Control Information :
 *  $Revision: 4771 $
 *  $Date: 2015-02-10 12:01:30 +0100 (Di, 10 Feb 2015) $
 *  $LastChangedBy: florian.zimmermann $
 ****************************************************************************
 * Change History (autogenerated):
 ****************************************************************************/
/*----------------------------------------------------------------------------------------------------------*/
/* Renesas D1x Platform gets platform constrained registerfile, default config for all other*/
/**/
#ifdef RENESAS_D1X
  #include "davehd_registerfile_ree.h"
#else
  #include "davehd_registerfile_default.h"
#endif

